version: "3"

services:
  query-node:
    build:
      context: ../..
      target: test-project
    restart: unless-stopped
    environment:
      - DB_NAME=processor-db
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - GRAPHQL_SERVER_PORT=4000
    depends_on:
      - hydra-processor
    command: yarn query-node:start

  hydra-processor:
    build:
      context: ../..
      target: test-project
    environment:
      - DB_NAME=processor-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - INDEXER_ENDPOINT_URL=http://hydra-indexer-gateway:8080/v1/graphql
      - CHAIN_NODE=ws://node-template:9944
      - POLL_INTERVAL_MS=500 # refresh every second
      - DEBUG=hydra*
      - VERBOSE=true
    depends_on:
      - hydra-indexer-gateway
    command: >
      sh -c "npm run typegen && \
             npm run build && \
             npm run db:create && \
             npx hydra-cli db:create-migration Initial && \
             npm run db:reset && \
             npm run processor:start"

  hydra-indexer:
    build:
      context: ../..
      target: indexer
    restart: always
    environment:
      - DB_NAME=indexer-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - NEW_BLOCK_TIMEOUT_SEC=150000
      - WS_PROVIDER_ENDPOINT_URI=ws://node-template:9944/
      - REDIS_URI=redis://redis:6379/0
      - DEBUG=index-builder:*,hydra-indexer:*
      - TYPES_JSON=typedefs.json
    volumes:
      - ./fixtures/typedefs.json:/hydra-indexer/typedefs.json
    command: >
      sh -c "yarn db:bootstrap && yarn start:prod"
    depends_on:
      - db
      - redis
      - node-template

  hydra-indexer-gateway:
    build:
      context: ../..
      target: indexer-gateway
    restart: always
    depends_on:
      - redis
      - db
      - hydra-indexer-status-service
      - hydra-indexer
    environment:
      DEV_MODE: "true"
      DB_NAME: indexer-db
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      DB_PORT: 5432
      HYDRA_INDEXER_STATUS_SERVICE: http://hydra-indexer-status-service:8081/status
    ports:
      - "8080:8080"

  hydra-indexer-status-service:
    build:
      context: ../..
      target: indexer-status-service
    depends_on:
      - redis
    environment:
      REDIS_URI: redis://redis:6379/0
      PORT: 8081

  node-template:
    image: paritytech/substrate-playground-template-node-template:sha-7212614
    command: ["./target/release/node-template", "--dev", "--tmp", "--ws-external"]

  redis:
    image: redis:6.0-alpine
    restart: always

  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    # command: ["postgres", "-c", "log_statement=all"]
